# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YMImangePick_clip_demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YMImangePick_clip_demo

pod 'TOCropViewController’;
pod 'TZImagePickerController’;
pod 'RSKImageCropper’;
pod "MWPhotoBrowser"

  target 'YMImangePick_clip_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YMImangePick_clip_demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
